// lib/core/database/app_database.dart
//
// AppDatabase — the single Drift database instance for the entire app.
//
// Usage (via Riverpod — see database_provider.dart):
//   final db = ref.watch(appDatabaseProvider);
//   final warehouses = await db.warehouseDao.getAllWarehouses();
//
// Schema versioning:
//   Bump schemaVersion and add a MigrationStrategy.onUpgrade handler for
//   every production schema change. Never edit existing column definitions
//   without a migration.

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:warehouse_app/features/additional.data/location/data/tables/locations_tables.dart';
import 'package:warehouse_app/features/warehouse/data/daos/warehouse_dao.dart';
import 'package:warehouse_app/features/warehouse/data/tables/warehouse_table.dart';
import 'package:warehouse_app/features/worker/data/daos/worker_dao.dart';
import 'package:warehouse_app/features/worker/data/tables/worker_table.dart';
import 'package:warehouse_app/features/additional.data/crop/data/daos/crop_dao.dart';
import 'package:warehouse_app/features/additional.data/crop/data/tables/crop_table.dart';
import 'package:warehouse_app/features/farmer/data/daos/farmer_dao.dart';
import 'package:warehouse_app/features/farmer/data/tables/farmer_tables.dart';
import 'package:warehouse_app/features/harvest/data/daos/harvest_dao.dart';
import 'package:warehouse_app/features/harvest/data/tables/harvest_tables.dart';

import 'tables/app_tables.dart';
import 'daos/inventory_dao.dart';
import 'daos/sync_queue_dao.dart';
import 'daos/audit_log_dao.dart';
import 'package:warehouse_app/features/additional.data/location/data/daos/region_dao.dart';
import 'package:warehouse_app/features/additional.data/location/data/daos/district_dao.dart';
import 'package:warehouse_app/features/additional.data/location/data/daos/ward_dao.dart';
import 'package:warehouse_app/features/additional.data/location/data/daos/village_dao.dart';
import 'package:warehouse_app/features/additional.data/amcos/data/daos/amcos_dao.dart';
import 'package:warehouse_app/features/additional.data/amcos/data/tables/amcos_table.dart';

// ── Re-exports ──────────────────────────────────────────────────────────────
// Anything that imports app_database.dart should also get access to:
//  - Value / Value.absent() (used to build *Companion objects)
//  - All table classes (Users, Warehouses, etc.) from app_tables.dart
//  - All DAO classes (WorkerDao, WarehouseDao, InventoryDao, SyncQueueDao,
//    AuditLogDao, RegionDao, DistrictDao, WardDao, VillageDao) so
//    repositories/sync_engine don't need separate imports.
export 'package:drift/drift.dart' show Value;
export 'tables/app_tables.dart';
export 'daos/inventory_dao.dart';
export 'daos/sync_queue_dao.dart';
export 'daos/audit_log_dao.dart';
export 'package:warehouse_app/features/warehouse/data/daos/warehouse_dao.dart';
export 'package:warehouse_app/features/warehouse/data/tables/warehouse_table.dart';
export 'package:warehouse_app/features/worker/data/daos/worker_dao.dart';
export 'package:warehouse_app/features/worker/data/tables/worker_table.dart';
export 'package:warehouse_app/features/additional.data/crop/data/daos/crop_dao.dart';
export 'package:warehouse_app/features/additional.data/crop/data/tables/crop_table.dart';
export 'package:warehouse_app/features/farmer/data/daos/farmer_dao.dart';
export 'package:warehouse_app/features/farmer/data/tables/farmer_tables.dart';
export 'package:warehouse_app/features/harvest/data/daos/harvest_dao.dart';
export 'package:warehouse_app/features/harvest/data/tables/harvest_tables.dart';
export 'package:warehouse_app/features/additional.data/location/data/daos/region_dao.dart';
export 'package:warehouse_app/features/additional.data/location/data/daos/district_dao.dart';
export 'package:warehouse_app/features/additional.data/location/data/daos/ward_dao.dart';
export 'package:warehouse_app/features/additional.data/location/data/daos/village_dao.dart';
export 'package:warehouse_app/features/additional.data/amcos/data/daos/amcos_dao.dart';
export 'package:warehouse_app/features/additional.data/amcos/data/tables/amcos_table.dart';

// This file is generated by build_runner:
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Users,
    Warehouses,
    InventoryItems,
    StockMovements,
    SyncQueue,
    AuditLogs,
    RegionsTable,
    DistrictsTable,
    WardsTable,
    VillagesTable,
    AmcosTable,
    CropTable,
    Farmers,
    FarmerDependants,
    MeasurementUnits,
    CropGrades,
    FarmerHarvests,
    FarmerHarvestBags,
  ],
  daos: [
    WorkerDao,
    WarehouseDao,
    InventoryDao,
    SyncQueueDao,
    AuditLogDao,
    RegionDao,
    DistrictDao,
    WardDao,
    VillageDao,
    AmcosDao,
    CropDao,
    FarmerDao,
    HarvestDao,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? executor]) : super(executor ?? _openConnection());

  // ── DAO accessors ────────────────────────────────────────────────────────
  // (Generated by drift_dev — exposed here for documentation clarity.)
  //
  //   db.workerDao
  //   db.warehouseDao
  //   db.inventoryDao
  //   db.syncQueueDao
  //   db.auditLogDao

  // ── Schema version ───────────────────────────────────────────────────────

  @override
  int get schemaVersion => 8;

  // ── Migrations ───────────────────────────────────────────────────────────

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (m) async {
        // Create all tables on a fresh install.
        await m.createAll();
      },
      onUpgrade: (m, from, to) async {
        // v1 → v2: create the four location reference-data tables.
        if (from < 2) {
          await m.createTable(regionsTable);
          await m.createTable(districtsTable);
          await m.createTable(wardsTable);
          await m.createTable(villagesTable);
        }

        // v2 → v3: create the amcos table and its DAO-backed accessors.
        if (from < 3) {
          await m.createTable(amcosTable);
        }

        // v3 → v4: rebuild amcos table without the MCU foreign-key reference
        // because the MCU table is not stored in this local Drift database.
        if (from < 4) {
          await m.deleteTable(amcosTable.actualTableName);
          await m.createTable(amcosTable);
        }

        // v4 → v5: add the warehouse sync fields required by the UUID-based
        // sync flow for owner/worker warehouse synchronization.
        if (from < 5) {
          await m.addColumn(warehouses, warehouses.uuid);
          await m.addColumn(warehouses, warehouses.synced);
          await m.addColumn(warehouses, warehouses.syncAction);
          await m.addColumn(warehouses, warehouses.createdAt);
          await m.addColumn(warehouses, warehouses.updatedAt);
          await m.addColumn(warehouses, warehouses.deletedAt);
          await m.addColumn(warehouses, warehouses.syncStatus);
        }

        // v5 -> v6: align local worker records with the create-worker API
        // payload while preserving the existing worker profile data.
        if (from < 6) {
          await customStatement(
            'ALTER TABLE users RENAME COLUMN name TO full_name',
          );
          await m.addColumn(users, users.phoneNumber);
          await m.addColumn(users, users.password);
          await m.addColumn(users, users.mcu);
          await m.addColumn(users, users.amcos);
        }

        // v6 -> v7: worker-side farmer registration cache and crop lookup
        // tables used by POST /farmers and POST /farmer-dependants/{id}.
        if (from < 7) {
          await m.createTable(cropTable);
          await m.createTable(farmers);
          await m.createTable(farmerDependants);
        }

        // v7 -> v8: worker-side farmer harvest capture, bag details, and
        // reference data needed by POST /farmer-harvests.
        if (from < 8) {
          await m.createTable(measurementUnits);
          await m.createTable(cropGrades);
          await m.createTable(farmerHarvests);
          await m.createTable(farmerHarvestBags);
        }
      },
      beforeOpen: (details) async {
        // Enable WAL mode for better concurrent read/write performance.
        await customStatement('PRAGMA journal_mode = WAL');
        // Enforce foreign key constraints.
        await customStatement('PRAGMA foreign_keys = ON');
      },
    );
  }

  // ── Utility — wipe all data (used during testing / logout) ───────────────

  /// Deletes every row from every table. Preserves the schema.
  /// Call on logout so the next user starts clean.
  Future<void> clearAllData() {
    return transaction(() async {
      // Delete in reverse dependency order to avoid FK violations.
      await delete(auditLogs).go();
      await delete(syncQueue).go();
      await delete(farmerHarvestBags).go();
      await delete(farmerHarvests).go();
      await delete(stockMovements).go();
      await delete(inventoryItems).go();
      await delete(farmerDependants).go();
      await delete(farmers).go();
      await delete(cropGrades).go();
      await delete(measurementUnits).go();
      await delete(warehouses).go();
      await delete(users).go();
      await delete(cropTable).go();
      await delete(amcosTable).go();
      // Location reference-data tables (leaf → root order).
      await delete(villagesTable).go();
      await delete(wardsTable).go();
      await delete(districtsTable).go();
      await delete(regionsTable).go();
    });
  }
}

// ── SQLite connection ──────────────────────────────────────────────────────

QueryExecutor _openConnection() {
  // drift_flutter picks the right SQLite implementation per platform:
  //   Android/iOS → sqlite3_flutter_libs native lib
  //   Desktop     → OS sqlite3
  return driftDatabase(
    name: 'warehouse_app',
    native: const DriftNativeOptions(
      // Shares the DB file across app restarts.
      shareAcrossIsolates: true,
    ),
  );
}

// ── Test helper ───────────────────────────────────────────────────────────

/// Returns an in-memory database for unit tests — no file I/O.
AppDatabase openInMemoryDatabase() {
  return AppDatabase(NativeDatabase.memory(logStatements: false));
}
